files:
  include: "scss/**/*.scss"
  ignore:
    - node_modules/**

syntax:
    include:
      - scss

options:
  optOut: false
  formatter: stylish
  merge-default-rules: false

resolvers:
  property-sort-order: 2
  empty-line-between-blocks: 2
  final-newline: 2

rules:
  quotes:
    -
      style: 'single'
  pseudo-element: 2
  placeholder-in-extend: 0
  one-declaration-per-line: 2
  no-url-domains: 1
  no-invalid-hex: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 1
  url-quotes: 1
  no-transition-all: 1
  no-important: 1
  no-ids: 0
  no-extends: 0
  no-attribute-selectors: 0
  property-units:
    -
      global: ['em', 'px', 'rem']
  nesting-depth:
    -
      max-depth: 5
  mixins-before-declarations:
    -
      exclude: ['media-breakpoint-up', 'media-breakpoint-down']
  hex-notation:
    -
      style: uppercase
  empty-args:
    -
      include: true
  attribute-quotes:
    -
      include: true
  property-sort-order:
    - 2
    -
      order: 'smacss' # https://github.com/sasstools/sass-lint/blob/master/docs/rules/property-sort-order.md
